name: Create pull request
on:
  push:
    branches:
      - version_update
jobs:
  prForMasterBranch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Reset master branch
        run: |
          git fetch origin version_update_2:version_update_2
          git reset --hard version_update_2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: update master branch
          title: Update master branch
          branch: temp
          delete-branch: true
          # assignees: user-you-want-to
          # reviewers: user-you-want-to